version: "3.2"

services:
    pihole1: 
        image: somerepo:sometag
        hostname: pihole1
        environment:
            - TZ='Americas/Toronto'
            - WEBPASSWORD="password"
            - FTL_CMD=debug
            - DNSMASQ_LISTENING=all
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - "/path/to/etc-pihole:/etc/pihole"
            - "/patch/to/etc-dnsmasq.d:/etc/dnsmaq.d"
        restart_policy:
            - unless-stopped
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.dns == dns.1


