
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://dkr01:9200", "http://dkr02:9201", "http://dkr04:9202",]
xpack.monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: changeme
